##########################################################################################

x-common-log-config: &default_config
  networks:
    - layer_batch_prod
  logging:
    driver: "json-file"
    options:
      max-file: "5"
      max-size: "10m"

##########################################################################################
#########################    DEPLOYMENT CONFIGS FOR NODES    #############################

x-common-network: &common_network
  networks:
    - cluster_swarm_hadoop

x-common-restart-default: &common_restart_policy
  restart_policy:
    condition: on-failure


x-common-deploy-master: &common_deploy_master
  <<: *common_network
  deploy:
    <<: *common_restart_policy
    placement:
      constraints: [node.hostname == dadaia-desktop]

x-common-deploy-worker-1: &common_deploy_worker_1
  <<: *common_network
  deploy:
    <<: *common_restart_policy
    placement:
      constraints: [node.hostname == dadaia-HP-ZBook-15-G2]

x-common-deploy-worker-2: &common_deploy_worker_2
  <<: *common_network
  deploy:
    <<: *common_restart_policy
    placement:
      constraints: [node.hostname == dadaia-server-2]

x-common-deploy-worker-3: &common_deploy_worker_3
  <<: *common_network
  deploy:
    <<: *common_restart_policy
    placement:
      constraints: [node.hostname == dadaia-server]


services:

  # APACHE HADOOP SERVICES
  namenode:
    image: marcoaureliomenezes/dm-hadoop-namenode:1.0.0
    <<: *default_config
    ports:
      - 9870:9870
      - 9000:9000
    volumes:
      - hadoop_labs_namenode_prod_vol:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=dm_v3_chain_explorer_prod
    <<: *common_deploy_worker_1

  resourcemanager:
    image: marcoaureliomenezes/dm-hadoop-resourcemanager:1.0.0
    <<: *default_config
    ports:
      - 18088:8088
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870"
    env_file:
      - ./hadoop.env
    <<: *common_deploy_worker_1

  datanode-1:
    image: marcoaureliomenezes/dm-hadoop-datanode:1.0.0
    <<: *default_config
    volumes:
      - hadoop_labs_datanode_1_prod_vol:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env
    <<: *common_deploy_worker_1

  datanode-2:
    image: marcoaureliomenezes/dm-hadoop-datanode:1.0.0
    <<: *default_config
    volumes:
      - hadoop_labs_datanode_2_prod_vol:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env
    <<: *common_deploy_worker_2


  datanode-3:
    image: marcoaureliomenezes/dm-hadoop-datanode:1.0.0
    <<: *default_config
    volumes:
      - hadoop_labs_datanode_3_prod_vol:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env
    <<: *common_deploy_worker_3

  nodemanager-1:
    image: marcoaureliomenezes/dm-hadoop-nodemanager:1.0.0
    <<: *default_config
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 resourcemanager:8088 datanode-1:9864 datanode-2:9864 datanode-3:9864"
    env_file:
      - ./hadoop.env
    <<: *common_deploy_worker_1

  nodemanager-2:
    image: marcoaureliomenezes/dm-hadoop-nodemanager:1.0.0
    <<: *default_config
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 resourcemanager:8088 datanode-1:9864  datanode-2:9864 datanode-3:9864"
    env_file:
      - ./hadoop.env
    <<: *common_deploy_worker_2

  nodemanager-3:
    image: marcoaureliomenezes/dm-hadoop-nodemanager:1.0.0
    <<: *default_config
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 resourcemanager:8088 datanode-1:9864 datanode-2:9864 datanode-3:9864"
    env_file:
      - ./hadoop.env
    <<: *common_deploy_worker_3

  historyserver:
    image: marcoaureliomenezes/dm-hadoop-historyserver:1.0.0
    <<: *default_config
    ports:
      - 18188:8188
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 resourcemanager:8088 datanode-1:9864 datanode-2:9864 datanode-3:9864"
    volumes:
      - hadoop_labs_history_server_prod_vol:/hadoop/yarn/timeline
    env_file:
      - ./hadoop.env
    <<: *common_deploy_worker_1


  # POSTGRES DATABASE FOR HIVE METASTORE AND HUE
  postgres:
    image: marcoaureliomenezes/dm-postgres:1.0.0
    <<: *default_config
    environment:
      - POSTGRES_USER=postgres
    volumes:
      - hadoop_labs_pg_hive_hue_prod_vol:/var/lib/postgresql/data
    <<: *common_deploy_worker_3

  hive-metastore:
    image: marcoaureliomenezes/dm-hive-base:1.0.0
    <<: *default_config
    command: /opt/hive/bin/hive --service metastore
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode-1:9864 datanode-2:9864 datanode-3:9864 postgres:5432"
    ports:
      - "9083:9083"
    env_file:
      - ./hadoop-hive.env
    <<: *common_deploy_worker_1

  hive-server:
    image: marcoaureliomenezes/dm-hive-base:1.0.0
    <<: *default_config
    env_file:
      - ./hadoop-hive.env
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://postgres:5432/metastore"
      SERVICE_PRECONDITION: "hive-metastore:9083"
    <<: *common_deploy_worker_1


  presto-coordinator:
    image: shawnzhu/prestodb:0.181
    <<: *default_config
    <<: *common_deploy_worker_1


  hue-webui:
    image: marcoaureliomenezes/dm-hue-webui:1.0.0
    <<: *default_config
    ports:
      - "32762:8888"
    # volumes:
    #   - ../mnt/hue/hue.ini:/usr/share/hue/desktop/conf/z-hue.ini
    environment:
      SERVICE_PRECONDITION: "hive-server:10000 postgres:5432"
    <<: *common_deploy_master

networks:
  cluster_swarm_hadoop:
    external: true


volumes:
  hadoop_labs_namenode_prod_vol:
  hadoop_labs_datanode_1_prod_vol:
  hadoop_labs_datanode_2_prod_vol:
  hadoop_labs_datanode_3_prod_vol:
  hadoop_labs_history_server_prod_vol:
  hadoop_labs_pg_hive_hue_prod_vol: