---
version: '3'

x-common-network: &common_network
  networks:
    - learning_kafka

services:


  # simple_producer:
  #   build: ../docker/1_producers
  #   container_name: simple_producer
  #   environment:
  #     KAFKA_BROKERS: 'broker0:29092,broker1:29093,broker2:29094'
  #     SCHEMA_REGISTRY_URL: 'http://schema-registry:8081'
  #     KAFKA_TOPIC: 'simple_producer.clients'
  #     FREQUENCY: 1
  #   <<: *common_network
  #   restart: always
  #   volumes:
  #     - ../docker/1_producers/src:/app
  #   entrypoint: "python /app/simple_producer.py"


  avro_producer:
    build: ../docker/1_producers
    container_name: avro_producer
    environment:
      KAFKA_BROKERS: 'broker0:29092,broker1:29093,broker2:29094'
      SCHEMA_REGISTRY_URL: 'http://schema-registry:8081'
      KAFKA_TOPIC: 'avro_serialized.clients'
      FREQUENCY: 1
    <<: *common_network
    restart: always
    volumes:
      - ../docker/1_producers/src:/app
    entrypoint: "python /app/avro_producer.py"


  avro_consumer:
    build: ../docker/2_consumers
    container_name: avro_consumer
    environment:
      KAFKA_BROKERS: 'broker0:29092,broker1:29093,broker2:29094'
      SCHEMA_REGISTRY_URL: 'http://schema-registry:8081'
      KAFKA_TOPIC: 'avro_serialized.clients'
      FREQUENCY: 1
    <<: *common_network
    restart: always
    volumes:
      - ../docker/2_consumers/src:/app
    #entrypoint: "python /app/avro_producer.py"

networks:
  learning_kafka:
    driver: bridge