version: '3'

x-common-network: &common_network
  networks:
    - learning_kafka

#################################################################
################    DEFINIÇÃO DOS SERVIÇOS    ###################
#################################################################

services:

  spark-master:
    image: docker.io/bitnami/spark:3.5
    container_name: spark-master
    <<: *common-network
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - '8080:8080'
    healthcheck:
      test: [ "CMD", "ls" ]
      <<: *default_healthcheck
      

  spark-worker:
    image: docker.io/bitnami/spark:3.5
    <<: *common-network
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=4
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    healthcheck:
      test: [ "CMD", "ls" ]
      <<: *default_healthcheck


networks:
  learning_kafka:
    name: learning_kafka
    driver: bridge